-- Insert 100 entries for the Category table
INSERT INTO Category (CategoryID, Description) VALUES
('cat001', 'House Cleaning'),
('cat002', 'Office Cleaning'),
('cat003', 'Window Cleaning'),
('cat004', 'Carpet Cleaning'),
('cat005', 'Laundry Service'),
('cat006', 'Move-In/Move-Out Cleaning'),
('cat007', 'Post-Construction Cleaning'),
('cat008', 'Airbnb Cleaning'),
('cat009', 'Pet Cleaning'),
('cat010', 'Steam Cleaning'),
('cat011', 'Pressure Washing'),
('cat012', 'Deep Cleaning'),
('cat013', 'Residential Cleaning'),
('cat014', 'Commercial Cleaning'),
('cat015', 'Event Cleanup'),
('cat016', 'Apartment Cleaning'),
('cat017', 'Spring Cleaning'),
('cat018', 'Oven Cleaning'),
('cat019', 'Fridge Cleaning'),
('cat020', 'Tile and Grout Cleaning'),
('cat021', 'Disinfection Services'),
('cat022', 'Trash Removal'),
('cat023', 'Office Disinfection'),
('cat024', 'Bed Bug Treatment'),
('cat025', 'Mold Remediation'),
('cat026', 'Furnace Cleaning'),
('cat027', 'Chimney Cleaning'),
('cat028', 'Gutter Cleaning'),
('cat029', 'Patio Cleaning'),
('cat030', 'Hoarding Cleanup'),
('cat031', 'Sofa Cleaning'),
('cat032', 'Curtain Cleaning'),
('cat033', 'Mattress Cleaning'),
('cat034', 'Ceiling Fan Cleaning'),
('cat035', 'Kitchen Cleaning'),
('cat036', 'Bathroom Cleaning'),
('cat037', 'Vacuuming Service'),
('cat038', 'Household Organization'),
('cat039', 'Basement Cleaning'),
('cat040', 'Attic Cleaning'),
('cat041', 'Upholstery Cleaning'),
('cat042', 'Pressure Washing for Driveways'),
('cat043', 'Exterior House Cleaning'),
('cat044', 'Deck Cleaning'),
('cat045', 'Hardwood Floor Cleaning'),
('cat046', 'Tile Floor Cleaning'),
('cat047', 'Carpet Stain Removal'),
('cat048', 'Post-Party Cleanup'),
('cat049', 'Regular House Cleaning'),
('cat050', 'Luxury Cleaning Services'),
('cat051', 'Disaster Cleanup'),
('cat052', 'Emergency Cleaning'),
('cat053', 'Odor Removal Services'),
('cat054', 'Window Washing'),
('cat055', 'Pool Cleaning'),
('cat056', 'Construction Site Cleaning'),
('cat057', 'Solar Panel Cleaning'),
('cat058', 'Moving Services'),
('cat059', 'Packing and Unpacking'),
('cat060', 'Furniture Moving'),
('cat061', 'House Painting'),
('cat062', 'Interior Cleaning'),
('cat063', 'Exterior Window Washing'),
('cat064', 'Tree Trimming'),
('cat065', 'Landscaping Services'),
('cat066', 'Pressure Cleaning for Walls'),
('cat067', 'Commercial Floor Cleaning'),
('cat068', 'Car Detailing'),
('cat069', 'Air Duct Cleaning'),
('cat070', 'Water Damage Cleanup'),
('cat071', 'Post-Tenant Cleaning'),
('cat072', 'Refrigerator Cleaning'),
('cat073', 'Seasonal Cleaning'),
('cat074', 'Personalized Cleaning'),
('cat075', 'Event Decorating and Cleanup'),
('cat076', 'Commercial Disinfection'),
('cat077', 'Maid Services'),
('cat078', 'Gardening Services'),
('cat079', 'Green Cleaning Services'),
('cat080', 'Pet Grooming and Cleaning'),
('cat081', 'Wall Cleaning'),
('cat082', 'Floor Polishing'),
('cat083', 'Grout Sealing'),
('cat084', 'Bathroom Sanitization'),
('cat085', 'Mold Prevention'),
('cat086', 'Pest Control Services'),
('cat087', 'Holiday Cleanup'),
('cat088', 'Laundry Pickup and Delivery'),
('cat089', 'Weekly Cleaning Services'),
('cat090', 'Kitchen Organization'),
('cat091', 'Cleaning for Senior Citizens'),
('cat092', 'Household Maintenance'),
('cat093', 'Portable Toilet Cleaning'),
('cat094', 'Handyman Services'),
('cat095', 'Small Appliance Cleaning'),
('cat096', 'Construction Waste Removal'),
('cat097', 'Eco-Friendly Cleaning'),
('cat098', 'Home Renovation Cleanup'),
('cat099', 'Storm Cleanup'),
('cat100', 'Beach House Cleaning');
