-- Insert into Login_Details for User_Admin
INSERT INTO Login_Details (Email, Password) VALUES
('User_Admin', 'admin1@example.com', 'passwordUA1'),
('User_Admin', 'admin2@example.com', 'passwordUA2'),
('User_Admin', 'admin3@example.com', 'passwordUA3'),
('User_Admin', 'admin4@example.com', 'passwordUA4'),
('User_Admin', 'admin5@example.com', 'passwordUA5'),
('User_Admin', 'admin6@example.com', 'passwordUA6'),
('User_Admin', 'admin7@example.com', 'passwordUA7'),
('User_Admin', 'admin8@example.com', 'passwordUA8'),
('User_Admin', 'admin9@example.com', 'passwordUA9'),
('User_Admin', 'admin10@example.com', 'passwordUA10'),
('User_Admin', 'admin11@example.com', 'passwordUA11'),
('User_Admin', 'admin12@example.com', 'passwordUA12'),
('User_Admin', 'admin13@example.com', 'passwordUA13'),
('User_Admin', 'admin14@example.com', 'passwordUA14'),
('User_Admin', 'admin15@example.com', 'passwordUA15'),
('User_Admin', 'admin16@example.com', 'passwordUA16'),
('User_Admin', 'admin17@example.com', 'passwordUA17'),
('User_Admin', 'admin18@example.com', 'passwordUA18'),
('User_Admin', 'admin19@example.com', 'passwordUA19'),
('User_Admin', 'admin20@example.com', 'passwordUA20'),
('User_Admin', 'admin21@example.com', 'passwordUA21'),
('User_Admin', 'admin22@example.com', 'passwordUA22'),
('User_Admin', 'admin23@example.com', 'passwordUA23'),
('User_Admin', 'admin24@example.com', 'passwordUA24'),
('User_Admin', 'admin25@example.com', 'passwordUA25');

-- Insert into Login_Details for Cleaner
INSERT INTO Login_Details (Email, Password) VALUES
('Cleaner', 'cleaner1@example.com', 'passwordCL1'),
('Cleaner', 'cleaner2@example.com', 'passwordCL2'),
('Cleaner', 'cleaner3@example.com', 'passwordCL3'),
('Cleaner', 'cleaner4@example.com', 'passwordCL4'),
('Cleaner', 'cleaner5@example.com', 'passwordCL5'),
('Cleaner', 'cleaner6@example.com', 'passwordCL6'),
('Cleaner', 'cleaner7@example.com', 'passwordCL7'),
('Cleaner', 'cleaner8@example.com', 'passwordCL8'),
('Cleaner', 'cleaner9@example.com', 'passwordCL9'),
('Cleaner', 'cleaner10@example.com', 'passwordCL10'),
('Cleaner', 'cleaner11@example.com', 'passwordCL11'),
('Cleaner', 'cleaner12@example.com', 'passwordCL12'),
('Cleaner', 'cleaner13@example.com', 'passwordCL13'),
('Cleaner', 'cleaner14@example.com', 'passwordCL14'),
('Cleaner', 'cleaner15@example.com', 'passwordCL15'),
('Cleaner', 'cleaner16@example.com', 'passwordCL16'),
('Cleaner', 'cleaner17@example.com', 'passwordCL17'),
('Cleaner', 'cleaner18@example.com', 'passwordCL18'),
('Cleaner', 'cleaner19@example.com', 'passwordCL19'),
('Cleaner', 'cleaner20@example.com', 'passwordCL20'),
('Cleaner', 'cleaner21@example.com', 'passwordCL21'),
('Cleaner', 'cleaner22@example.com', 'passwordCL22'),
('Cleaner', 'cleaner23@example.com', 'passwordCL23'),
('Cleaner', 'cleaner24@example.com', 'passwordCL24'),
('Cleaner', 'cleaner25@example.com', 'passwordCL25');

-- Insert into Login_Details for HomeOwner
INSERT INTO Login_Details (Email, Password) VALUES
('HomeOwner', 'homeowner1@example.com', 'passwordHO1'),
('HomeOwner', 'homeowner2@example.com', 'passwordHO2'),
('HomeOwner', 'homeowner3@example.com', 'passwordHO3'),
('HomeOwner', 'homeowner4@example.com', 'passwordHO4'),
('HomeOwner', 'homeowner5@example.com', 'passwordHO5'),
('HomeOwner', 'homeowner6@example.com', 'passwordHO6'),
('HomeOwner', 'homeowner7@example.com', 'passwordHO7'),
('HomeOwner', 'homeowner8@example.com', 'passwordHO8'),
('HomeOwner', 'homeowner9@example.com', 'passwordHO9'),
('HomeOwner', 'homeowner10@example.com', 'passwordHO10'),
('HomeOwner', 'homeowner11@example.com', 'passwordHO11'),
('HomeOwner', 'homeowner12@example.com', 'passwordHO12'),
('HomeOwner', 'homeowner13@example.com', 'passwordHO13'),
('HomeOwner', 'homeowner14@example.com', 'passwordHO14'),
('HomeOwner', 'homeowner15@example.com', 'passwordHO15'),
('HomeOwner', 'homeowner16@example.com', 'passwordHO16'),
('HomeOwner', 'homeowner17@example.com', 'passwordHO17'),
('HomeOwner', 'homeowner18@example.com', 'passwordHO18'),
('HomeOwner', 'homeowner19@example.com', 'passwordHO19'),
('HomeOwner', 'homeowner20@example.com', 'passwordHO20'),
('HomeOwner', 'homeowner21@example.com', 'passwordHO21'),
('HomeOwner', 'homeowner22@example.com', 'passwordHO22'),
('HomeOwner', 'homeowner23@example.com', 'passwordHO23'),
('HomeOwner', 'homeowner24@example.com', 'passwordHO24'),
('HomeOwner', 'homeowner25@example.com', 'passwordHO25');

-- Insert into Login_Details for PlatformManager
INSERT INTO Login_Details (Email, Password) VALUES
('PlatformManager', 'manager1@example.com', 'passwordPM1'),
('PlatformManager', 'manager2@example.com', 'passwordPM2'),
('PlatformManager', 'manager3@example.com', 'passwordPM3'),
('PlatformManager', 'manager4@example.com', 'passwordPM4'),
('PlatformManager', 'manager5@example.com', 'passwordPM5'),
('PlatformManager', 'manager6@example.com', 'passwordPM6'),
('PlatformManager', 'manager7@example.com', 'passwordPM7'),
('PlatformManager', 'manager8@example.com', 'passwordPM8'),
('PlatformManager', 'manager9@example.com', 'passwordPM9'),
('PlatformManager', 'manager10@example.com', 'passwordPM10'),
('PlatformManager', 'manager11@example.com', 'passwordPM11'),
('PlatformManager', 'manager12@example.com', 'passwordPM12'),
('PlatformManager', 'manager13@example.com', 'passwordPM13'),
('PlatformManager', 'manager14@example.com', 'passwordPM14'),
('PlatformManager', 'manager15@example.com', 'passwordPM15'),
('PlatformManager', 'manager16@example.com', 'passwordPM16'),
('PlatformManager', 'manager17@example.com', 'passwordPM17'),
('PlatformManager', 'manager18@example.com', 'passwordPM18'),
('PlatformManager', 'manager19@example.com', 'passwordPM19'),
('PlatformManager', 'manager20@example.com', 'passwordPM20'),
('PlatformManager', 'manager21@example.com', 'passwordPM21'),
('PlatformManager', 'manager22@example.com', 'passwordPM22'),
('PlatformManager', 'manager23@example.com', 'passwordPM23'),
('PlatformManager', 'manager24@example.com', 'passwordPM24'),
('PlatformManager', 'manager25@example.com', 'passwordPM25');

-- Insert statements for User_Admin (25 entries)
INSERT INTO "User" (UserID, Username, UserProfile, Email) VALUES
('UA001', 'adminuser1', 'User_Admin', 'admin1@example.com'),
('UA002', 'adminuser2', 'User_Admin', 'admin2@example.com'),
('UA003', 'adminuser3', 'User_Admin', 'admin3@example.com'),
('UA004', 'adminuser4', 'User_Admin', 'admin4@example.com'),
('UA005', 'adminuser5', 'User_Admin', 'admin5@example.com'),
('UA006', 'adminuser6', 'User_Admin', 'admin6@example.com'),
('UA007', 'adminuser7', 'User_Admin', 'admin7@example.com'),
('UA008', 'adminuser8', 'User_Admin', 'admin8@example.com'),
('UA009', 'adminuser9', 'User_Admin', 'admin9@example.com'),
('UA010', 'adminuser10', 'User_Admin', 'admin10@example.com'),
('UA011', 'adminuser11', 'User_Admin', 'admin11@example.com'),
('UA012', 'adminuser12', 'User_Admin', 'admin12@example.com'),
('UA013', 'adminuser13', 'User_Admin', 'admin13@example.com'),
('UA014', 'adminuser14', 'User_Admin', 'admin14@example.com'),
('UA015', 'adminuser15', 'User_Admin', 'admin15@example.com'),
('UA016', 'adminuser16', 'User_Admin', 'admin16@example.com'),
('UA017', 'adminuser17', 'User_Admin', 'admin17@example.com'),
('UA018', 'adminuser18', 'User_Admin', 'admin18@example.com'),
('UA019', 'adminuser19', 'User_Admin', 'admin19@example.com'),
('UA020', 'adminuser20', 'User_Admin', 'admin20@example.com'),
('UA021', 'adminuser21', 'User_Admin', 'admin21@example.com'),
('UA022', 'adminuser22', 'User_Admin', 'admin22@example.com'),
('UA023', 'adminuser23', 'User_Admin', 'admin23@example.com'),
('UA024', 'adminuser24', 'User_Admin', 'admin24@example.com'),
('UA025', 'adminuser25', 'User_Admin', 'admin25@example.com');

-- Insert into User_Admin
INSERT INTO User_Admin (UserID) SELECT UserID FROM "User" WHERE UserProfile = 'User_Admin';

-- Insert statements for Cleaner (25 entries)
INSERT INTO "User" (UserID, Username, UserProfile, Email) VALUES
('CL001', 'cleaner1', 'Cleaner', 'cleaner1@example.com'),
('CL002', 'cleaner2', 'Cleaner', 'cleaner2@example.com'),
('CL003', 'cleaner3', 'Cleaner', 'cleaner3@example.com'),
('CL004', 'cleaner4', 'Cleaner', 'cleaner4@example.com'),
('CL005', 'cleaner5', 'Cleaner', 'cleaner5@example.com'),
('CL006', 'cleaner6', 'Cleaner', 'cleaner6@example.com'),
('CL007', 'cleaner7', 'Cleaner', 'cleaner7@example.com'),
('CL008', 'cleaner8', 'Cleaner', 'cleaner8@example.com'),
('CL009', 'cleaner9', 'Cleaner', 'cleaner9@example.com'),
('CL010', 'cleaner10', 'Cleaner', 'cleaner10@example.com'),
('CL011', 'cleaner11', 'Cleaner', 'cleaner11@example.com'),
('CL012', 'cleaner12', 'Cleaner', 'cleaner12@example.com'),
('CL013', 'cleaner13', 'Cleaner', 'cleaner13@example.com'),
('CL014', 'cleaner14', 'Cleaner', 'cleaner14@example.com'),
('CL015', 'cleaner15', 'Cleaner', 'cleaner15@example.com'),
('CL016', 'cleaner16', 'Cleaner', 'cleaner16@example.com'),
('CL017', 'cleaner17', 'Cleaner', 'cleaner17@example.com'),
('CL018', 'cleaner18', 'Cleaner', 'cleaner18@example.com'),
('CL019', 'cleaner19', 'Cleaner', 'cleaner19@example.com'),
('CL020', 'cleaner20', 'Cleaner', 'cleaner20@example.com'),
('CL021', 'cleaner21', 'Cleaner', 'cleaner21@example.com'),
('CL022', 'cleaner22', 'Cleaner', 'cleaner22@example.com'),
('CL023', 'cleaner23', 'Cleaner', 'cleaner23@example.com'),
('CL024', 'cleaner24', 'Cleaner', 'cleaner24@example.com'),
('CL025', 'cleaner25', 'Cleaner', 'cleaner25@example.com');

-- Insert into Cleaner
INSERT INTO Cleaner (UserID) SELECT UserID FROM "User" WHERE UserProfile = 'Cleaner';

-- Insert statements for HomeOwner (25 entries)
INSERT INTO "User" (UserID, Username, UserProfile, Email) VALUES
('HO001', 'homeowner1', 'HomeOwner', 'homeowner1@example.com'),
('HO002', 'homeowner2', 'HomeOwner', 'homeowner2@example.com'),
('HO003', 'homeowner3', 'HomeOwner', 'homeowner3@example.com'),
('HO004', 'homeowner4', 'HomeOwner', 'homeowner4@example.com'),
('HO005', 'homeowner5', 'HomeOwner', 'homeowner5@example.com'),
('HO006', 'homeowner6', 'HomeOwner', 'homeowner6@example.com'),
('HO007', 'homeowner7', 'HomeOwner', 'homeowner7@example.com'),
('HO008', 'homeowner8', 'HomeOwner', 'homeowner8@example.com'),
('HO009', 'homeowner9', 'HomeOwner', 'homeowner9@example.com'),
('HO010', 'homeowner10', 'HomeOwner', 'homeowner10@example.com'),
('HO011', 'homeowner11', 'HomeOwner', 'homeowner11@example.com'),
('HO012', 'homeowner12', 'HomeOwner', 'homeowner12@example.com'),
('HO013', 'homeowner13', 'HomeOwner', 'homeowner13@example.com'),
('HO014', 'homeowner14', 'HomeOwner', 'homeowner14@example.com'),
('HO015', 'homeowner15', 'HomeOwner', 'homeowner15@example.com'),
('HO016', 'homeowner16', 'HomeOwner', 'homeowner16@example.com'),
('HO017', 'homeowner17', 'HomeOwner', 'homeowner17@example.com'),
('HO018', 'homeowner18', 'HomeOwner', 'homeowner18@example.com'),
('HO019', 'homeowner19', 'HomeOwner', 'homeowner19@example.com'),
('HO020', 'homeowner20', 'HomeOwner', 'homeowner20@example.com'),
('HO021', 'homeowner21', 'HomeOwner', 'homeowner21@example.com'),
('HO022', 'homeowner22', 'HomeOwner', 'homeowner22@example.com'),
('HO023', 'homeowner23', 'HomeOwner', 'homeowner23@example.com'),
('HO024', 'homeowner24', 'HomeOwner', 'homeowner24@example.com'),
('HO025', 'homeowner25', 'HomeOwner', 'homeowner25@example.com');

-- Insert into HomeOwner (with address)
INSERT INTO HomeOwner (UserID, Address) 
SELECT UserID, '123 Home Street' FROM "User" WHERE UserProfile = 'HomeOwner';

-- Insert statements for PlatformManager (25 entries)
INSERT INTO "User" (UserID, Username, UserProfile, Email) VALUES
('PM001', 'manager1', 'PlatformManager', 'manager1@example.com'),
('PM002', 'manager2', 'PlatformManager', 'manager2@example.com'),
('PM003', 'manager3', 'PlatformManager', 'manager3@example.com'),
('PM004', 'manager4', 'PlatformManager', 'manager4@example.com'),
('PM005', 'manager5', 'PlatformManager', 'manager5@example.com'),
('PM006', 'manager6', 'PlatformManager', 'manager6@example.com'),
('PM007', 'manager7', 'PlatformManager', 'manager7@example.com'),
('PM008', 'manager8', 'PlatformManager', 'manager8@example.com'),
('PM009', 'manager9', 'PlatformManager', 'manager9@example.com'),
('PM010', 'manager10', 'PlatformManager', 'manager10@example.com'),
('PM011', 'manager11', 'PlatformManager', 'manager11@example.com'),
('PM012', 'manager12', 'PlatformManager', 'manager12@example.com'),
('PM013', 'manager13', 'PlatformManager', 'manager13@example.com'),
('PM014', 'manager14', 'PlatformManager', 'manager14@example.com'),
('PM015', 'manager15', 'PlatformManager', 'manager15@example.com'),
('PM016', 'manager16', 'PlatformManager', 'manager16@example.com'),
('PM017', 'manager17', 'PlatformManager', 'manager17@example.com'),
('PM018', 'manager18', 'PlatformManager', 'manager18@example.com'),
('PM019', 'manager19', 'PlatformManager', 'manager19@example.com'),
('PM020', 'manager20', 'PlatformManager', 'manager20@example.com'),
('PM021', 'manager21', 'PlatformManager', 'manager21@example.com'),
('PM022', 'manager22', 'PlatformManager', 'manager22@example.com'),
('PM023', 'manager23', 'PlatformManager', 'manager23@example.com'),
('PM024', 'manager24', 'PlatformManager', 'manager24@example.com'),
('PM025', 'manager25', 'PlatformManager', 'manager25@example.com');

-- Insert into PlatformManager
INSERT INTO PlatformManager (UserID) SELECT UserID FROM "User" WHERE UserProfile = 'PlatformManager';